version: '3'
services:
  maria-db:
    image: mariadb:10.3.6
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: estacionamento
    ports:
      - 3306:3306

  estacionamento:
    image: com.matera.wcc/projeto:latest
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL
      - DATABASE_USERNAME
      - DATABASE_PASSWORD
      - SPRING_PROFILES_ACTIVE
    depends_on:
      - maria-db
    restart: on-failure
